// <auto-generated />
using Day02.OneToOnePP.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day02.OneToOnePP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426172134_V01")]
    partial class V01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day02.OneToOnePP.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Day02.OneToOnePP.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Day02.OneToOnePP.Models.EmployeeCar", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "CarId");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeCars");
                });

            modelBuilder.Entity("Day02.OneToOnePP.Models.EmployeeCar", b =>
                {
                    b.HasOne("Day02.OneToOnePP.Models.Car", "Car")
                        .WithOne("EmployeeCar")
                        .HasForeignKey("Day02.OneToOnePP.Models.EmployeeCar", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Day02.OneToOnePP.Models.Employee", "Employee")
                        .WithOne("EmployeeCar")
                        .HasForeignKey("Day02.OneToOnePP.Models.EmployeeCar", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Day02.OneToOnePP.Models.Car", b =>
                {
                    b.Navigation("EmployeeCar")
                        .IsRequired();
                });

            modelBuilder.Entity("Day02.OneToOnePP.Models.Employee", b =>
                {
                    b.Navigation("EmployeeCar")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
